version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5620
    deploy:
      resources:
        limits:
          cpus: '0.5'  # Limit CPU usage to 50%
          memory: '512M'  # Limit memory usage to 512 MB
    networks:
      - transcendence

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "5620:5620"
    deploy:
      resources:
        limits:
          cpus: '0.5'  # Limit CPU usage to 50%
          memory: '512M'  # Limit memory usage to 512 MB
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge
