# Use Python as the base image
FROM python:3.12.0b3-slim

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose port 5620 to the outside world
EXPOSE 5620

# Command to run the application
CMD ["python", "main.py"]
